### ISSUE TITLE
Desktop app: Showcase change in links list

### ISSUE THREAD

**Issue by Miloua91** [Miloua91/clipwarp#15]
Showcase change in links list when a link gets added in the desktop app.

Suggestion: A counter to showcase the change or just changing the color of tab that has the new link.

![Group 2](https://github.com/user-attachments/assets/3814b88d-070c-438e-89b1-16b849a1e0e3)

**Comment by HazemAbdo** [comment]
@Miloua91 I'd like to work on this feature.

**Comment by Miloua91** [comment]
@HazemAbdo Sure! Also don't hesitate to ask if you have any questions.
