### ISSUE TITLE
Mobile app: Add light mode

### ISSUE THREAD

**Issue by Miloua91** [Miloua91/clipwarp#16]
Add light mode to the mobile app.

**Comment by HazemAbdo** [comment]
@Miloua91 Can you please assign this issue to me?

**Comment by Miloua91** [comment]
@HazemAbdo to make your work easier, you need to change these two major colors in **app.tsx**, and add the choice to change between dark and light mode in settings

```
const bgColor = "#252422";
const cardColor = "#403d39";
```

then use nativewind to change the rest of the colors like text and such. feel free to ask me any question
